name: fhirant
description: FHIR ANT — a FHIR R4 server in your pocket.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  drift: ^2.29.0
  fhir_r4: ^0.8.0
  fhirant_db:
    path: ../fhirant_db
  fhirant_logging:
    path: ../fhirant_logging
  fhirant_secure_storage:
    path: ../fhirant_secure_storage
  fhirant_server:
    path: ../fhirant_server
  flutter:
    sdk: flutter
  flutter_foreground_task: ^8.13.4
  flutter_secure_storage: ^10.0.0
  network_info_plus: ^6.1.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.0
  sqlite3: ^3.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
hooks:
  user_defines:
    sqlite3:
      source: sqlite3mc

flutter:
  uses-material-design: true
  assets:
    - assets/
