name: fhirant_secure_storage
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  basic_utils: ^5.8.2
  crypto: ^3.0.3
  fhirant_logging:
    path: ../fhirant_logging
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
