name: fhirant
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  fhir_r4: 
    path: ../../fhir_r4
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.5
  sqlcipher_flutter_libs: ^0.6.4
  sqlite3: ^2.5.0


dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/