name: fhirant
description: Fast Healthcare Interoperability Resources Agile Networking Tool
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  crypto: ^3.0.6
  dart_jsonwebtoken: ^2.15.0
  fhir_r4:
    path: ../fhir_r4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  json_view: ^0.4.2
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.1
  sqlcipher_flutter_libs: ^0.6.4
  sqlite3: ^2.7.1

dependency_overrides:
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - mimic-fhir/
    - fhir-assets/
