name: fhirant_server
description: A standalone server for standalone use with the FhirAntDb or in combination with the FhirAnt Flutter Interface.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  antlr4: ^4.13.2
  args: ^2.7.0
  cicada:
    path: ../../../cicada/cicada
  drift: ^2.29.0
  fhir_r4:
    path: ../../../fhir_r4/packages/fhir_r4
  fhir_r4_cql:
    path: ../../../fhir_r4/packages/fhir_r4_cql
  fhir_r4_path:
    path: ../../../fhir_r4/packages/fhir_r4_path
  fhir_r4_mapping:
    path: ../../../fhir_r4/packages/fhir_r4_mapping
  fhir_r4_validation:
    path: ../../../fhir_r4/packages/fhir_r4_validation
  fhirant_db:
    path: ../fhirant_db
  fhirant_logging:
    path: ../fhirant_logging
  crypto: ^3.0.3
  dart_jsonwebtoken: ^3.3.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_rate_limiter: ^1.0.1
  sqlite3: ^2.4.6
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.25.8
  mocktail: ^1.0.0

dependency_overrides:
  fhir_r4:
    path: ../../../fhir_r4/packages/fhir_r4
  fhir_r4_cql:
    path: ../../../fhir_r4/packages/fhir_r4_cql
  fhir_r4_path:
    path: ../../../fhir_r4/packages/fhir_r4_path
  fhir_r4_mapping:
    path: ../../../fhir_r4/packages/fhir_r4_mapping
  fhir_r4_validation:
    path: ../../../fhir_r4/packages/fhir_r4_validation
