name: fhirant_db
description: Fast Healthcare Interoperability Resources Agile Networking Tool
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  drift: ^2.29.0
  fhir_r4:
    path: ../../../fhir_r4/packages/fhir_r4
  fhir_r4_db:
    path: ../../../fhir_r4/packages/fhir_r4_db
  path: ^1.9.1
  sqlite3: ^2.4.6

dev_dependencies:
  lints: ^5.1.1
  mocktail: ^1.0.4
  test: ^1.25.8

dependency_overrides:
  fhir_r4:
    path: ../../../fhir_r4/packages/fhir_r4
