import 'package:fhirant_db/fhirant_db.dart';

/// Whether [payload], a verified JWT, was issued under an earlier token
/// generation than the account holds now, and is therefore over.
///
/// OWASP Session Management Cheat Sheet, "Renew the Session ID After Any
/// Privilege Level Change" (raw markdown read 2026-09-19, verbatim): "The
/// session ID must be renewed or regenerated by the web application after
/// any privilege level change within the associated user session. ...
/// Common scenarios to consider include; password changes, permission
/// changes, or switching from a regular user role to an administrator
/// role" and "the old or previous session ID must be destroyed". A JWT
/// cannot be destroyed, so the account carries a token generation
/// ([User.tokenGeneration]), every token carries the generation it was
/// issued under (`gen`), and the password, role, scope and activation
/// changes of REVIEW-2026-09-17 A14 move the account's on. A token with
/// no `gen` claim is from before this and counts as generation 0.
///
/// A counter rather than an instant: a token issued in the same second as
/// the change would be on the wrong side of a timestamp, and the change
/// itself hands the caller a token of the new generation.
bool tokenPredatesAccount(Map<String, dynamic> payload, User account) {
  final gen = payload['gen'];
  final issuedUnder = gen is int ? gen : 0;
  return issuedUnder < account.tokenGeneration;
}
