// Real Argon2id hash when the token is minted.
@Timeout(Duration(minutes: 3))
library;

import 'dart:convert';
import 'dart:io';

import 'package:fhirant_db/fhirant_db.dart';
import 'package:shelf/shelf.dart';
import 'package:test/test.dart';

import 'test_helpers.dart';

/// Every registered FHIR route, sent a request that cannot succeed, fails
/// with an OperationOutcome.
///
/// R4B http.html, read whole 2026-09-21, verbatim: "In case of failure,
/// servers SHOULD always return a body that contains an OperationOutcome
/// resource." Measured before this test existed (tool/review_2026-09-17/
/// error_shape/01_error_shapes.tsv): 59 of 59 failures already did, so this
/// guards a property rather than fixing one.
///
/// Not covered, and permitted: a path no route matches gets the router's
/// plain-text 404. The same page, verbatim: "The OperationOutcome may be
/// returned with any HTTP 4xx or 5xx response, but this is not required -
/// many of these errors may be generated by generic server frameworks
/// underlying a FHIR server." (02_methods.tsv: `PATCH /_history`,
/// `TRACE /Patient`.)
///
/// The route list is read from the registrations, as in
/// every_route_is_guarded_test.dart.
void main() {
  late FhirAntDb db;
  late Handler handler;
  late Directory exportDir;
  late String adminToken;

  setUp(() async {
    exportDir = await Directory.systemTemp.createTemp('outcome');
    final server = await createTestServer(exportDir: exportDir.path);
    db = server.db;
    handler = server.handler;
    adminToken = await issueTestToken(
      db,
      username: 'outcome-admin',
      role: 'admin',
      scopes: ['system/*.*'],
    );
  });

  tearDown(() async {
    await db.close();
    await exportDir.delete(recursive: true);
  });

  test('every FHIR route fails with an OperationOutcome', () async {
    final source = File('lib/src/fhirant_server.dart').readAsStringSync();
    final routes = RegExp(
      r"\.\.(get|post|put|delete|patch|all|head|mount|add)\(\s*r?'([^']+)'",
      dotAll: true,
    ).allMatches(source).map(
          (m) => (verb: m.group(1)!.toUpperCase(), path: m.group(2)!),
        );
    final notOutcome = <String>[];
    var failures = 0;
    for (final route in routes) {
      // Not FHIR endpoints: OAuth and account routes answer RFC 6749-style
      // JSON errors, and these four have no failure to provoke.
      if (route.path.startsWith('/auth/') ||
          route.path.startsWith('/admin/') ||
          const {'/', '/favicon.ico', '/health', '/ws'}.contains(route.path)) {
        continue;
      }
      final verb = route.verb == 'ALL' ? 'POST' : route.verb;
      final url = route.path
          .replaceAll('<resourceType>', 'Patient')
          .replaceAll('<compartmentType>', 'Patient')
          .replaceAll('<compartmentId>', 'nope')
          .replaceAll('<groupId>', 'nope')
          .replaceAll('<jobId>', 'nope')
          .replaceAll('<fileName>', 'nope.ndjson')
          .replaceAll('<vid>', '999')
          .replaceAll('<id>', 'nope');
      final response = await handler(
        testRequest(
          verb,
          url,
          authToken: adminToken,
          headers: {'content-type': 'application/fhir+json'},
          body: verb == 'GET' || verb == 'DELETE' ? null : '{"not":"fhir"}',
        ),
      );
      if (response.statusCode < 400) continue;
      failures++;
      final body = await response.readAsString();
      Object? decoded;
      try {
        decoded = jsonDecode(body);
      } on FormatException {
        decoded = null;
      }
      final isOutcome =
          decoded is Map && decoded['resourceType'] == 'OperationOutcome';
      if (!isOutcome) {
        notOutcome.add('$verb ${route.path} -> ${response.statusCode}');
      }
    }
    expect(notOutcome, isEmpty);
    // Control: the requests really did fail, so the loop measured something.
    expect(failures, greaterThan(50));
  });
}
